package wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 22-10-2015
//
//---------------------------------------------------



import org.ksoap2.serialization.*;
import java.util.Vector;
import java.util.Hashtable;


public class ArrayOfCustomerSurveyXml extends Vector<CustomerSurveyXml> implements KvmSerializable
{
    
    public ArrayOfCustomerSurveyXml(){}
    
    public ArrayOfCustomerSurveyXml(Object inObj, ExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        SoapObject soapObject=(SoapObject)inObj;
        int size = soapObject.getPropertyCount();
        for (int i0=0;i0< size;i0++)
        {
            Object obj = soapObject.getProperty(i0);
            if (obj!=null && obj instanceof AttributeContainer)
            {
                AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                CustomerSurveyXml j1= (CustomerSurveyXml)__envelope.get(j, CustomerSurveyXml.class);
                add(j1);
            }
        }
}
    
    @Override
    public Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "CustomerSurveyXml";
        info.type = CustomerSurveyXml.class;
    	info.namespace= "http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel";
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}