package wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 22-10-2015
//
//---------------------------------------------------



import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.lang.reflect.Constructor;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;

public class ExtendedSoapSerializationEnvelope extends SoapSerializationEnvelope {
    static HashMap< String,Class> classNames = new HashMap< String, Class>();
    static {
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfAuthtokenXmlkZUuIBUF", RequestResultOfAuthtokenXmlkZUuIBUF.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^AuthtokenXml", AuthtokenXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfboolean", RequestResultOfboolean.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfArrayOfLocationXmlkZUuIBUF", RequestResultOfArrayOfLocationXmlkZUuIBUF.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^LocationXml", LocationXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^TimeslotXml", TimeslotXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^AppointmentXml", AppointmentXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^AppointmentResultsXml", AppointmentResultsXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^PatientXml", PatientXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ServiceProviderXml", ServiceProviderXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfArrayOfTimeslotXmlkZUuIBUF", RequestResultOfArrayOfTimeslotXmlkZUuIBUF.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfArrayOfServiceProviderXmlkZUuIBUF", RequestResultOfArrayOfServiceProviderXmlkZUuIBUF.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfArrayOfstringuHEDJ7Dj", RequestResultOfArrayOfstringuHEDJ7Dj.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfArrayOfHospitalXmlkZUuIBUF", RequestResultOfArrayOfHospitalXmlkZUuIBUF.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^HospitalXml", HospitalXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfArrayOfCustomerSurveyXmlkZUuIBUF", RequestResultOfArrayOfCustomerSurveyXmlkZUuIBUF.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^CustomerSurveyXml", CustomerSurveyXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^CustomerSurveyResultXml", CustomerSurveyResultXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^CustomerSurveyQuestionXml", CustomerSurveyQuestionXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^PatientReminderXml", PatientReminderXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfArrayOfPatientReminderXmlkZUuIBUF", RequestResultOfArrayOfPatientReminderXmlkZUuIBUF.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^RequestResultOfArrayOfInfoRecordXmlkZUuIBUF", RequestResultOfArrayOfInfoRecordXmlkZUuIBUF.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^InfoRecordXml", InfoRecordXml.class);
        classNames.put("http://tempuri.org/^^PatientGetInfo", PatientGetInfo.class);
        classNames.put("http://tempuri.org/^^PatientGetInfoResponse", PatientGetInfoResponse.class);
        classNames.put("http://schemas.microsoft.com/2003/10/Serialization/Arrays^^ArrayOfstring", ArrayOfstring.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ArrayOfLocationXml", ArrayOfLocationXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ArrayOfAppointmentXml", ArrayOfAppointmentXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ArrayOfTimeslotXml", ArrayOfTimeslotXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ArrayOfServiceProviderXml", ArrayOfServiceProviderXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ArrayOfHospitalXml", ArrayOfHospitalXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ArrayOfCustomerSurveyXml", ArrayOfCustomerSurveyXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ArrayOfCustomerSurveyResultXml", ArrayOfCustomerSurveyResultXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ArrayOfPatientReminderXml", ArrayOfPatientReminderXml.class);
        classNames.put("http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel^^ArrayOfInfoRecordXml", ArrayOfInfoRecordXml.class);
    }   

    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public ExtendedSoapSerializationEnvelope() {
        this(SoapEnvelope.VER11);
    }

    public ExtendedSoapSerializationEnvelope(int soapVersion) {
        super(soapVersion);
        implicitTypes = true;
        setAddAdornments(false);
        new MarshalGuid().register(this);
        new MarshalFloat().register(this);
    }

    

    @Override
    protected void writeProperty(XmlSerializer writer, Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
        Object[] qName = getInfo(null, obj);
        if (!type.multiRef && qName[2] == null )
        {
            
            if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=String.class)) {
                String xmlName= Helper.getKeyByValue(classNames, obj.getClass());
                if(xmlName!=null) {
                    String[] parts = xmlName.split("\\^\\^");
                    String prefix = writer.getPrefix(parts[0], true);
                    writer.attribute(xsi, TYPE_LABEL, prefix + ":" + parts[1]);
                }
                else
                {
                    if(type.type instanceof String) {
                        String xsdPrefix = writer.getPrefix(xsd, true);
                        String myType = (String) type.type;
                        String[] parts = myType.split("\\^\\^");
                        if (parts.length == 2) {
                            xsdPrefix = writer.getPrefix(parts[0], true);
                            myType = parts[1];
                        }

                        writer.attribute(xsi, TYPE_LABEL, xsdPrefix + ":" + myType);
                    }
                    else
                    {
                        String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }

                }
            }
            //super.writeProperty(writer,obj,type);

            //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
            //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
            writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
        }
        else {
            super.writeProperty(writer, obj, type);
        }
    }

    public SoapObject GetExceptionDetail(Element detailElement,String exceptionElementNS,String exceptionElementName)
    {
        int index=detailElement.indexOf(exceptionElementNS,exceptionElementName,0);
        if(index>-1)
        {
            Element errorElement=detailElement.getElement(index);
            return GetSoapObject(errorElement);
        }
        return null;
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public Object GetHeader(Element detailElement) {
        if(detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    
    public Object get(Object soap,Class cl)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(soap instanceof  Vector)
            {
                Constructor ctor = cl.getConstructor(Object.class, ExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
            {
                if(soap instanceof SoapObject)
                {
                    if(cl ==SoapObject.class)
                    {
                        return soap;
                    }
                    String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                Constructor ctor = cl.getConstructor(Object.class, ExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }

} 

