package wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 10-12-2015
//
//---------------------------------------------------



public interface IServiceEvents
{
    void Starting();

    void Completed(OperationResult result);
}
