package wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 10-12-2015
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class PatientGetPaymentInformationResponse extends AttributeContainer implements KvmSerializable
{

    
    public RequestResultOfPatientPaymentXml PatientGetPaymentInformationResult;

    public PatientGetPaymentInformationResponse()
    {
    }

    public PatientGetPaymentInformationResponse(Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("PatientGetPaymentInformationResult"))
                {
                    Object j = obj;
                    this.PatientGetPaymentInformationResult = (RequestResultOfPatientPaymentXml)__envelope.get(j, RequestResultOfPatientPaymentXml.class);
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.PatientGetPaymentInformationResult!=null?this.PatientGetPaymentInformationResult:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = RequestResultOfPatientPaymentXml.class;
            info.name = "PatientGetPaymentInformationResult";
            info.namespace= "http://tempuri.org/";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
