package wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 13-11-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class PatientGetInfo extends AttributeContainer implements KvmSerializable
{

    
    public AuthtokenXml authToken;
    
    public Integer offset;
    
    public Integer limit;

    public PatientGetInfo()
    {
    }

    public PatientGetInfo(Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("authToken"))
                {
                    Object j = obj;
                    this.authToken = (AuthtokenXml)__envelope.get(j, AuthtokenXml.class);
                    continue;
                }
                if (info.name.equals("offset"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.offset = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this.offset = (Integer)obj;
                    }
                    continue;
                }
                if (info.name.equals("limit"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.limit = Integer.parseInt(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Integer){
                        this.limit = (Integer)obj;
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.authToken!=null?this.authToken:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.offset!=null?this.offset:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.limit!=null?this.limit:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = AuthtokenXml.class;
            info.name = "authToken";
            info.namespace= "http://tempuri.org/";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "offset";
            info.namespace= "http://tempuri.org/";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "limit";
            info.namespace= "http://tempuri.org/";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
